### ISSUE TITLE
Add a civic.json file

### ISSUE THREAD

**Issue by stvnrlly** [civictechdc/open211#5]
A [civic.json file](http://codefordc.org/resources/specification.html) provides information about this project that's not included in the Github metadata. The full details of the format are [here](http://codefordc.org/resources/specification.html). Just put it in the root of your repo and we'll automatically display that info on the projects page.

Code for DC also has a tool to help put the file together [here](http://codefordc.org/resources/builder.html), and a validator to make sure everything's in the right place [here](http://codefordc.org/resources/validator.html).

(Also, since Code for DC is tracking this project, any issues tagged with `help wanted` will show up on http://codefordc.org/projects/helpwanted.html. If you are stuck on something, try that!)

**Comment by greggish** [comment]
@ajschumacher halp

**Comment by ajschumacher** [comment]
@greggish is there an Open211 logo or something?

For the moment, dropping top-level key "thumbnailUrl".

**Comment by ajschumacher** [comment]
@greggish what's the status of the project?

"Ideation"? "Alpha"? "Beta"? "Production"? "Archival"?

@stvnrlly the descriptions of these seem broken on http://codefordc.org/resources/specification.html; there are only two descriptions for five levels.

@greggish I'm putting "Alpha" unless I hear otherwise.

**Comment by ajschumacher** [comment]
Hmm I actually don't know what you want for most of these, @greggish...

`bornAt`? `geography`? `politicalEntity`? `communityPartner`? `type`? `data`? `needs`?

These are all top-level things that you can add in. Follow http://codefordc.org/resources/specification.html

**Comment by ajschumacher** [comment]
I'll say there's one category and it's "Open Data"; you can add more if you want.

**Comment by ajschumacher** [comment]
okay apparently github doesn't pick up on refs in pull request titles; I just opened #6 and you'll have a `civic.json` as soon as you merge that in, @greggish, and then you can update it to have all the data it should

**Comment by ajschumacher** [comment]
I'm done here, I think; I'll leave the issue for you to track and close when you're satisfied, @greggish! Happy Saturday!

**Comment by stvnrlly** [comment]
@ajschumacher re: the descriptions: they came from the original [specs](https://github.com/BetaNYC/civic.json/blob/master/specification.md). I'm happy to improve them, but I'll probably need to crowd-source some descriptions.

**Comment by greggish** [comment]
Um we don't have an official logo. We do have some options tho.

[One idea](https://drive.google.com/open?id=0B-5CZ4ZLjTHqY0czOVdubW9TSjVmRDJnXzZhZXM5ellIWHFJ&authuser=0)

(https://drive.google.com/open?id=0B-5CZ4ZLjTHqY0czOVdubW9TSjVmRDJnXzZhZXM5ellIWHFJ&authuser=0)
['Community Health Advocate'](https://drive.google.com/open?id=0B-5CZ4ZLjTHqal9jdm94TzdBNzg&authuser=0) from the Noun Project (public domain)

[DC Service Connect logo](http://dcopen211website.herokuapp.com/assets/smc_connect_logo.png) from
last year's Open Data Day

Regretfully i might default to the Noun Project icon for now

**Comment by greggish** [comment]
I think i did a thing but i am still really confuzzled

**Comment by ajschumacher** [comment]
@greggish what do you think you did?

**Comment by ajschumacher** [comment]
@greggish step one is probably merging the open pull request #6, yes?

**Comment by greggish** [comment]
@ajschumacher ok i merged that. but if i was supposed to have done that
before i went in to edit your thing... then i just screwed up. thanks for
bearing with me as i am still learning all this.

**Comment by ajschumacher** [comment]
Hmm I'm not sure what the whole timeline has been; you could have pulled my branch and made further commits etc. before merging to gh-pages, but that's a good deal more work. I was thinking merge them edit would be easiest; as long as the current version looks the way you want then it's all gravy. @stvnrlly #gravy

**Comment by greggish** [comment]
@svnrlly how did i do

**Comment by ajschumacher** [comment]
@greggish I think this:

```
"categories": [
        {
            "category": "Open Data"
            "category": "Social services",
        }
],
```

should be like this

```
"categories": [
        {"category": "Open Data"},
        {"category": "Social services"}
],
```

also don't forget the t in @stvnrlly haha~

**Comment by greggish** [comment]
hokay! @ajschumacher @stvnrlly thx 4 halp

**Comment by stvnrlly** [comment]
Looks good:

![screen shot 2015-03-01 at 12 36 40 pm](https://cloud.githubusercontent.com/assets/4156602/6431978/b734089c-c00f-11e4-8b3c-e85020feb94a.png)

**Comment by ajschumacher** [comment]
@greggish do you want to close this issue now? we have valiantly fought the civic.json fight; now give us rest

**Comment by greggish** [comment]
@ajschumacher ugh, yes, thanks for the reminder. My first issue-closing!

**Comment by ajschumacher** [comment]
:+1: congrats! :smile:

**Comment by stvnrlly** [comment]
:fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks:
