### ISSUE TITLE
Broken main link to http://communityresourcedata.codefordc.org/

### ISSUE THREAD

**Issue by rlh100** [civictechdc/open211#7]
When I go to:
http://communityresourcedata.codefordc.org/

I get:
404 File not found

Fedora Linux user using Firefox if it matters

**Comment by greggish** [comment]
Hi there. Thanks for noticing. We [moved to this URL](https://openreferral.org/pilots/dc-open211/) and forgot to update the previous links.

muggle question: how can we set the old URL to redirect automatically? Or is that not possible. It was a jekyll page in the first place.

**Comment by greggish** [comment]
Hrm, I think that I may have fixed it by simply editing the URL in this repo. I hope that automatically shows up on http://codefordc.org/projects/ though its not there yet...

**Comment by rlh100** [comment]
thanks
